// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KRProyectoPizzeria.Migrations
{
    [DbContext(typeof(KRProyectoPizzeriaContext))]
    [Migration("20241127175912_KRProyectoPizzeria")]
    partial class KRProyectoPizzeria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KRProyectoPizzeria.Models.KRPizzeria", b =>
                {
                    b.Property<int>("idKRPizzeria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idKRPizzeria"));

                    b.Property<string>("KR_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KR_Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("KR_WithCocaCola")
                        .HasColumnType("bit");

                    b.HasKey("idKRPizzeria");

                    b.ToTable("KRPizzeria");
                });
#pragma warning restore 612, 618
        }
    }
}
